import Breadcrumbs from '../components/Breadcrumbs';
import Sidebar from '../components/Sidebar';
import { keyStages } from '../data/programs';

function Academics() {
  const sidebarLinks = [{ label: 'Curriculum Overview', path: '/school/academics#curriculum' },{ label: 'Learning Stages', path: '/school/academics#keystages' },{ label: 'Learning Areas', path: '/school/academics#subjects' },{ label: 'Assessment', path: '/school/academics#results' }];
  const subjects = [
    { faculty: 'Core Learning', subjects: ['English / Literacy','Mathematics / Numeracy','Science','Social Studies / Humanities'] },
    { faculty: 'Digital & Practical', subjects: ['ICT / Computing','STEM Projects','Practical Skills','Research & Projects'] },
    { faculty: 'Creative & Communication', subjects: ['Creative Arts','Music / Drama','Languages','Public Speaking'] },
    { faculty: 'Growth & Wellbeing', subjects: ['Physical Education','Character Education','Leadership','Clubs & Activities'] },
  ];
  return <div className="bg-school-cream"><div className="bg-oak-green text-white py-12"><div className="container-hotel px-4 md:px-6 lg:px-8"><Breadcrumbs items={[{ label: 'Academics' }]} /><h1 className="text-4xl font-serif font-bold">Academics</h1><p className="text-sage mt-2">A flexible academic presentation ready to be adapted to a school’s real curriculum.</p></div></div><div className="container-hotel py-12 px-4 md:px-6 lg:px-8"><div className="grid grid-cols-1 lg:grid-cols-4 gap-12"><div className="lg:col-span-1"><Sidebar title="In This Section" links={sidebarLinks} /></div><div className="lg:col-span-3 space-y-16">
    <section id="curriculum"><h2 className="text-3xl font-serif font-bold text-ink mb-6">Curriculum Overview</h2><p className="text-slate leading-relaxed mb-6">This demo intentionally avoids claiming a specific examination body or accreditation. A live school website would present the school’s verified curriculum, subjects, assessment framework, examination pathway, and learning approach here.</p><div className="overflow-x-auto"><table className="w-full bg-white border border-slate/20"><thead className="bg-oak-green text-white"><tr><th className="px-4 py-3 text-left text-sm">Stage</th><th className="px-4 py-3 text-left text-sm">Classes</th><th className="px-4 py-3 text-left text-sm">Level</th><th className="px-4 py-3 text-left text-sm">Description</th></tr></thead><tbody>{keyStages.map(stage => <tr key={stage.id} className="border-b border-slate/10 last:border-0"><td className="px-4 py-3 font-medium text-ink">{stage.stage}</td><td className="px-4 py-3 text-slate">{stage.years}</td><td className="px-4 py-3 text-slate">{stage.age}</td><td className="px-4 py-3 text-slate text-sm">{stage.description}</td></tr>)}</tbody></table></div></section>
    <section id="subjects"><h2 className="text-3xl font-serif font-bold text-ink mb-6">Learning Areas</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-6">{subjects.map(group => <div key={group.faculty} className="bg-white border border-slate/20 rounded-lg p-6"><h3 className="font-semibold text-oak-green mb-4">{group.faculty}</h3><ul className="space-y-2">{group.subjects.map(subject => <li key={subject} className="flex items-center text-slate"><span className="w-1.5 h-1.5 bg-gold rounded-full mr-3"/><span>{subject}</span></li>)}</ul></div>)}</div></section>
    <section id="results"><h2 className="text-3xl font-serif font-bold text-ink mb-6">Assessment & Results</h2><div className="bg-white border border-slate/20 rounded-xl p-8"><p className="text-slate leading-relaxed mb-5">A live site can present verified examination results, awards, assessment policies, report-card information, or links to a secure result portal. We do not use fabricated result percentages in the sales demo.</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="bg-soft-gray rounded-lg p-5"><p className="font-semibold text-ink">Continuous Assessment</p><p className="text-sm text-slate mt-1">Show the school’s actual assessment approach.</p></div><div className="bg-soft-gray rounded-lg p-5"><p className="font-semibold text-ink">External Examinations</p><p className="text-sm text-slate mt-1">List verified examination bodies where applicable.</p></div><div className="bg-soft-gray rounded-lg p-5"><p className="font-semibold text-ink">Result Portal</p><p className="text-sm text-slate mt-1">Can be integrated as an optional module.</p></div></div></div></section>
  </div></div></div></div>;
}
export default Academics;
