export const demoRegistry = {
  hotel: {
    slug: 'hotel',
    name: 'Meridian House',
    category: 'Hospitality',
    description: 'A premium luxury hotel experience for a private Ikoyi property, with rooms, dining, amenities, gallery and booking flows.',
    icon: '🏨',
    featured: true,
    ready: true,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'bronze',
    favicon: '/favicons/hotel.svg',
    title: 'Meridian House — Luxury Hotel in Ikoyi, Lagos',
    previewImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1600&q=82',
    previewEyebrow: 'IKOYI · LAGOS',
    previewHeadline: 'A Private Estate in the Heart of the City',
    previewSubline: 'Forty-eight rooms. One quiet address.',
    previewNav: ['Rooms', 'Dining', 'Amenities'],
    previewCta: 'Explore Rooms',
  },
  restaurant: {
    slug: 'restaurant',
    name: 'EMBER',
    category: 'Restaurant',
    description: 'A contemporary African restaurant website with menu, reservations, private dining, gallery and storytelling.',
    icon: '🍽️',
    featured: true,
    ready: true,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'red',
    favicon: '/favicons/restaurant.svg',
    title: 'EMBER — Contemporary African Kitchen',
    previewImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1600&q=82',
    previewEyebrow: 'MAITAMA · ABUJA',
    previewHeadline: 'EMBER',
    previewSubline: 'Contemporary African Kitchen · Where fire meets flavour',
    previewNav: ['Menu', 'About', 'Reservations'],
    previewCta: 'Reserve a Table',
  },
  school: {
    slug: 'school',
    name: 'Crestfield Academy',
    category: 'Education',
    description: 'A complete 2026/2027 school website demo with academics, admissions, school life, enquiries, WhatsApp and portal-ready flows.',
    icon: '🎓',
    featured: true,
    ready: true,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'blue',
    favicon: '/favicons/school.svg',
    title: 'Crestfield Academy — TKO Motions School Demo',
    previewImage: 'https://images.pexels.com/photos/1205651/pexels-photo-1205651.jpeg?w=1600&q=82',
    previewEyebrow: '2026/2027 ADMISSIONS',
    previewHeadline: 'A Strong Start for Every Learner',
    previewSubline: 'Admissions, academics, school life and parent enquiries presented in one clear, modern experience.',
    previewNav: ['Academics', 'Admissions', 'School Life'],
    previewCta: 'Explore Crestfield',
  },
  'real-estate': {
    slug: 'real-estate',
    name: 'Apex Properties Abuja',
    category: 'Real Estate',
    description: 'An Abuja property platform with listings, search, agents, property detail pages, enquiries and viewing requests.',
    icon: '🏠',
    featured: true,
    ready: true,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'green',
    favicon: '/favicons/real-estate.svg',
    title: 'Apex Properties Abuja — Real Estate Demo',
    previewImage: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?w=1600&q=82',
    previewEyebrow: 'ABUJA PROPERTY',
    previewHeadline: 'Find Your Perfect Property in Abuja',
    previewSubline: 'Premium homes, apartments and commercial spaces across the FCT.',
    previewNav: ['Buy', 'Rent', 'Agents'],
    previewCta: 'Search Properties',
  },
  logistics: {
    slug: 'logistics',
    name: 'SwiftRoute Logistics',
    category: 'Logistics',
    description: 'A technology-driven logistics website with delivery services, tracking, business solutions and quote flows.',
    icon: '🚚',
    featured: true,
    ready: true,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'orange',
    favicon: '/favicons/logistics.svg',
    title: 'SwiftRoute Logistics — TKO Motions Demo',
    previewImage: 'https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg?w=1600&q=82',
    previewEyebrow: 'MOVING BUSINESS FORWARD',
    previewHeadline: 'Reliable logistics across Nigeria',
    previewSubline: 'Delivery, fulfilment, warehousing and real-time tracking.',
    previewNav: ['Services', 'Tracking', 'Solutions'],
    previewCta: 'Get a Quote',
  },
  clinic: {
    slug: 'clinic',
    name: 'MediCore Abuja',
    category: 'Healthcare',
    description: 'A modern private clinic website with services, doctors, departments, health resources and appointment flows.',
    icon: '🏥',
    featured: true,
    ready: true,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'teal',
    favicon: '/favicons/clinic.svg',
    title: 'MediCore Abuja — Healthcare Demo',
    previewImage: 'https://images.unsplash.com/photo-1538108149393-fbbd81895973?auto=format&fit=crop&w=1600&q=82',
    previewEyebrow: 'PRIVATE MEDICAL CARE',
    previewHeadline: 'Healthcare that feels clearer, calmer, and more personal.',
    previewSubline: 'Expert clinicians, responsive support and a simpler patient journey.',
    previewNav: ['Services', 'Doctors', 'Appointment'],
    previewCta: 'Book an Appointment',
  },
  'law-firm': {
    slug: 'law-firm',
    name: 'Adeyemi & Partners',
    category: 'Legal',
    description: 'A corporate law firm website built around matter routing, practice areas, lawyers, insights and enquiries.',
    icon: '⚖️',
    featured: true,
    ready: true,
    techStack: ['React', 'Tailwind v4'],
    color: 'indigo',
    favicon: '/favicons/law-firm.svg',
    title: 'Adeyemi & Partners — Law Firm Demo',
    previewImage: '/images/law-firm-office.svg',
    previewEyebrow: 'FIND THE RIGHT ROUTE',
    previewHeadline: 'Clear counsel for decisions that carry weight.',
    previewSubline: 'Corporate counsel for organisations, boards, founders and investors.',
    previewNav: ['Practice Areas', 'People', 'Insights'],
    previewCta: 'Discuss a Matter',
  },
  construction: {
    slug: 'construction',
    name: 'Construction Demo',
    category: 'Construction',
    description: 'Construction demo source is not included in this archive.',
    icon: '🏗️',
    featured: false,
    ready: false,
    techStack: [],
    color: 'yellow',
    favicon: '/favicons/construction.svg',
    title: 'Construction — TKO Motions Demo',
  },
  beauty: {
    slug: 'beauty',
    name: 'Beauty Demo',
    category: 'Beauty',
    description: 'Beauty demo source is not included in this archive.',
    icon: '💄',
    featured: false,
    ready: false,
    techStack: [],
    color: 'pink',
    favicon: '/favicons/beauty.svg',
    title: 'Beauty — TKO Motions Demo',
  },
  ecommerce: {
    slug: 'ecommerce',
    name: 'Ecommerce Demo',
    category: 'Commerce',
    description: 'Ecommerce demo source is not included in this archive.',
    icon: '🛍️',
    featured: false,
    ready: false,
    techStack: [],
    color: 'purple',
    favicon: '/favicons/ecommerce.svg',
    title: 'Ecommerce — TKO Motions Demo',
  },
};

export const demosList = Object.values(demoRegistry);
