export const demoRegistry = {
  hotel: {
    slug: 'hotel',
    name: 'Meridian House',
    description: 'A premium luxury hotel website with sophisticated design and GSAP animations.',
    icon: '🏨',
    featured: true,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'bronze',
    favicon: '/favicons/hotel.svg',
    title: 'Meridian House — Luxury Hotel in Ikoyi, Lagos',
  },
  restaurant: {
    slug: 'restaurant',
    name: 'Restaurant Demo',
    description: 'A high-end restaurant website with menu management and reservations.',
    icon: '🍽️',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'red',
    favicon: '/favicons/restaurant.svg',
    title: 'Restaurant — TKO Motions Demo',
  },
  school: {
    slug: 'school',
    name: 'School Demo',
    description: 'An educational institution website with courses and admission info.',
    icon: '🎓',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'blue',
    favicon: '/favicons/school.svg',
    title: 'School — TKO Motions Demo',
  },
  'real-estate': {
    slug: 'real-estate',
    name: 'Real Estate Demo',
    description: 'A property listing website with search and virtual tours.',
    icon: '🏠',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'green',
    favicon: '/favicons/real-estate.svg',
    title: 'Real Estate — TKO Motions Demo',
  },
  logistics: {
    slug: 'logistics',
    name: 'Logistics Demo',
    description: 'A logistics company website with tracking and services.',
    icon: '🚚',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'orange',
    favicon: '/favicons/logistics.svg',
    title: 'Logistics — TKO Motions Demo',
  },
  clinic: {
    slug: 'clinic',
    name: 'Clinic Demo',
    description: 'A medical clinic website with appointments and doctors.',
    icon: '🏥',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'teal',
    favicon: '/favicons/clinic.svg',
    title: 'Clinic — TKO Motions Demo',
  },
  'law-firm': {
    slug: 'law-firm',
    name: 'Law Firm Demo',
    description: 'A law firm website with practice areas and attorneys.',
    icon: '⚖️',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'indigo',
    favicon: '/favicons/law-firm.svg',
    title: 'Law Firm — TKO Motions Demo',
  },
  construction: {
    slug: 'construction',
    name: 'Construction Demo',
    description: 'A construction company website with projects and services.',
    icon: '🏗️',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'yellow',
    favicon: '/favicons/construction.svg',
    title: 'Construction — TKO Motions Demo',
  },
  beauty: {
    slug: 'beauty',
    name: 'Beauty Demo',
    description: 'A beauty salon website with services and booking.',
    icon: '💄',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'pink',
    favicon: '/favicons/beauty.svg',
    title: 'Beauty — TKO Motions Demo',
  },
  ecommerce: {
    slug: 'ecommerce',
    name: 'Ecommerce Demo',
    description: 'An online store website with products and cart.',
    icon: '🛍️',
    featured: false,
    techStack: ['React', 'Tailwind v4', 'GSAP'],
    color: 'purple',
    favicon: '/favicons/ecommerce.svg',
    title: 'Ecommerce — TKO Motions Demo',
  },
};

export const demosList = Object.values(demoRegistry);